#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sat Sep  4 22:23:29 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.title = wx.Panel(self, wx.ID_ANY)
        self.menu = wx.Notebook(self, wx.ID_ANY)
        self.menu_home = wx.Panel(self.menu, wx.ID_ANY)
        self.menu_insert = wx.Panel(self.menu, wx.ID_ANY)
        self.menu_draw = wx.Panel(self.menu, wx.ID_ANY)
        self.menu_view = wx.Panel(self.menu, wx.ID_ANY)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.library_btn = wx.ToggleButton(self.panel_1, wx.ID_ANY, "")
        self.search_btn = wx.ToggleButton(self.panel_1, wx.ID_ANY, "")
        self.code_btn = wx.ToggleButton(self.panel_1, wx.ID_ANY, "")
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.base1 = wx.SplitterWindow(self, wx.ID_ANY)
        self.navigation_panel = wx.Panel(self.base1, wx.ID_ANY)
        self.notebook_chooser = wx.Panel(self.navigation_panel, wx.ID_ANY)
        self.choice_2 = wx.Choice(self.notebook_chooser, wx.ID_ANY, choices=["choice 1"])
        self.bitmap_button_1 = wx.BitmapButton(self.notebook_chooser, wx.ID_ANY, wx.Bitmap("/home/monees007/Projects/Notebook/assets/images/add_circle_outline_white_24dp.svg", wx.BITMAP_TYPE_ANY))
        self.navigator = wx.SplitterWindow(self.navigation_panel, wx.ID_ANY)
        self.section = wx.Panel(self.navigator, wx.ID_ANY)
        self.sections = wx.Panel(self.section, wx.ID_ANY)
        self.text_ctrl_1 = wx.TextCtrl(self.sections, wx.ID_ANY, "", style=wx.BORDER_NONE)
        self.add_section_btn = wx.Panel(self.section, wx.ID_ANY)
        self.topics = wx.Panel(self.navigator, wx.ID_ANY)
        self.sections_copy = wx.Panel(self.topics, wx.ID_ANY)
        self.add_section_btn_copy = wx.Panel(self.topics, wx.ID_ANY)
        self.workspace = wx.Panel(self.base1, wx.ID_ANY)
        self.panel_4 = wx.Panel(self.workspace, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        self.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.title.SetMinSize((-1, 58))
        self.title.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.menu_home.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.menu_insert.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.menu_draw.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.menu_view.SetMinSize((-1, 100))
        self.menu_view.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.menu.SetMinSize((-1, 89))
        self.menu.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.menu.SetForegroundColour(wx.Colour(255, 255, 255))
        self.library_btn.SetMinSize((40, 40))
        self.library_btn.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.library_btn.SetForegroundColour(wx.Colour(142, 35, 107))
        self.library_btn.SetBitmap(wx.Bitmap("/home/monees007/Projects/Notebook/assets/images/library_books_white_24dp.svg", wx.BITMAP_TYPE_ANY))
        self.search_btn.SetMinSize((40, 40))
        self.search_btn.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.search_btn.SetForegroundColour(wx.Colour(142, 35, 107))
        self.search_btn.SetBitmap(wx.Bitmap("/home/monees007/Projects/Notebook/assets/images/manage_search_white_24dp.svg", wx.BITMAP_TYPE_ANY))
        self.code_btn.SetMinSize((40, 40))
        self.code_btn.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.code_btn.SetForegroundColour(wx.Colour(142, 35, 107))
        self.code_btn.SetBitmap(wx.Bitmap("/home/monees007/Projects/Notebook/assets/images/code_white_24dp.svg", wx.BITMAP_TYPE_ANY))
        self.panel_2.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.panel_1.SetMinSize((41, -1))
        self.choice_2.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.choice_2.SetSelection(0)
        self.bitmap_button_1.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        self.notebook_chooser.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.sections.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.add_section_btn.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.section.Hide()
        self.sections_copy.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.add_section_btn_copy.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.navigator.SetMinimumPaneSize(20)
        self.panel_4.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.base1.SetMinimumPaneSize(20)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        base = wx.BoxSizer(wx.VERTICAL)
        sidebar = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        list_with_adder_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        section_list_copy = wx.BoxSizer(wx.VERTICAL)
        list_with_adder = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        section_list = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        label_1 = wx.StaticText(self.title, wx.ID_ANY, "<monees007>")
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Noto Sans Mono CJK TC"))
        sizer_7.Add(label_1, 0, wx.ALL | wx.FIXED_MINSIZE | wx.SHAPED, 10)
        self.title.SetSizer(sizer_7)
        base.Add(self.title, 0, wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 3)
        self.menu.AddPage(self.menu_home, "Home")
        self.menu.AddPage(self.menu_insert, "Insert")
        self.menu.AddPage(self.menu_draw, "Draw")
        self.menu.AddPage(self.menu_view, "View")
        base.Add(self.menu, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 3)
        sizer_3.Add(self.library_btn, 0, wx.ALL, 1)
        sizer_3.Add(self.search_btn, 0, wx.FIXED_MINSIZE | wx.LEFT | wx.RIGHT | wx.SHAPED | wx.TOP, 1)
        sizer_3.Add(self.code_btn, 0, wx.ALL | wx.FIXED_MINSIZE | wx.SHAPED, 1)
        sizer_3.Add(self.panel_2, 1, wx.ALL | wx.EXPAND, 3)
        self.panel_1.SetSizer(sizer_3)
        sidebar.Add(self.panel_1, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        sizer_9.Add(self.choice_2, 6, wx.ALL, 3)
        sizer_9.Add((20, 20), 12, wx.EXPAND, 0)
        sizer_9.Add(self.bitmap_button_1, 1, wx.ALL | wx.EXPAND, 3)
        self.notebook_chooser.SetSizer(sizer_9)
        sizer_8.Add(self.notebook_chooser, 0, wx.ALL | wx.EXPAND, 3)
        label_3 = wx.StaticText(self.sections, wx.ID_ANY, "Add Section")
        label_3.SetForegroundColour(wx.Colour(219, 112, 219))
        section_list.Add(label_3, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        label_4 = wx.StaticText(self.sections, wx.ID_ANY, "Add Section")
        label_4.SetForegroundColour(wx.Colour(219, 112, 219))
        section_list.Add(label_4, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        section_list.Add(self.text_ctrl_1, 0, wx.ALL | wx.EXPAND, 3)
        section_list.Add((20, 20), 1, wx.EXPAND, 0)
        self.sections.SetSizer(section_list)
        list_with_adder.Add(self.sections, 1, wx.ALL | wx.EXPAND, 3)
        bitmap_1 = wx.StaticBitmap(self.add_section_btn, wx.ID_ANY, wx.Bitmap("/home/monees007/Projects/Notebook/assets/images/add_circle_outline_white_24dp.svg", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetForegroundColour(wx.Colour(219, 112, 219))
        sizer_5.Add(bitmap_1, 0, wx.ALL, 6)
        label_2 = wx.StaticText(self.add_section_btn, wx.ID_ANY, "Add Section")
        label_2.SetForegroundColour(wx.Colour(219, 112, 219))
        sizer_5.Add(label_2, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        self.add_section_btn.SetSizer(sizer_5)
        list_with_adder.Add(self.add_section_btn, 0, wx.ALL | wx.EXPAND, 3)
        self.section.SetSizer(list_with_adder)
        label_6 = wx.StaticText(self.sections_copy, wx.ID_ANY, "Add Section")
        label_6.SetForegroundColour(wx.Colour(219, 112, 219))
        section_list_copy.Add(label_6, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        label_7 = wx.StaticText(self.sections_copy, wx.ID_ANY, "Add Section")
        label_7.SetForegroundColour(wx.Colour(219, 112, 219))
        section_list_copy.Add(label_7, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        label_8 = wx.StaticText(self.sections_copy, wx.ID_ANY, "Add Section")
        label_8.SetForegroundColour(wx.Colour(219, 112, 219))
        section_list_copy.Add(label_8, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        section_list_copy.Add((20, 20), 1, wx.EXPAND, 0)
        self.sections_copy.SetSizer(section_list_copy)
        list_with_adder_copy.Add(self.sections_copy, 1, wx.ALL | wx.EXPAND, 3)
        bitmap_2 = wx.StaticBitmap(self.add_section_btn_copy, wx.ID_ANY, wx.Bitmap("/home/monees007/Projects/Notebook/assets/images/add_circle_outline_white_24dp.svg", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetForegroundColour(wx.Colour(219, 112, 219))
        sizer_6.Add(bitmap_2, 0, wx.ALL, 6)
        label_9 = wx.StaticText(self.add_section_btn_copy, wx.ID_ANY, "Add Section")
        label_9.SetForegroundColour(wx.Colour(219, 112, 219))
        sizer_6.Add(label_9, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        self.add_section_btn_copy.SetSizer(sizer_6)
        list_with_adder_copy.Add(self.add_section_btn_copy, 0, wx.ALL | wx.EXPAND, 3)
        self.topics.SetSizer(list_with_adder_copy)
        self.navigator.SplitVertically(self.section, self.topics)
        sizer_8.Add(self.navigator, 3, wx.EXPAND, 0)
        self.navigation_panel.SetSizer(sizer_8)
        sizer_10.Add(self.panel_4, 4, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 3)
        self.workspace.SetSizer(sizer_10)
        self.base1.SplitVertically(self.navigation_panel, self.workspace)
        sidebar.Add(self.base1, 4, wx.EXPAND, 0)
        base.Add(sidebar, 16, wx.EXPAND, 0)
        self.SetSizer(base)
        base.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class list_item(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: list_item.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.SetSize((166, 38))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: list_item.__set_properties
        self.SetSize((166, 38))
        self.SetBackgroundColour(wx.Colour(18, 18, 18))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: list_item.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        label = wx.StaticText(self, wx.ID_ANY, "Section Title", style=wx.ALIGN_CENTER)
        label.SetForegroundColour(wx.Colour(219, 112, 219))
        sizer.Add(label, 0, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 6)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

# end of class list_item

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((407, 245))
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_7 = wx.Button(self, wx.ID_ANY, "Create Notebook")
        self.button_6 = wx.Button(self, wx.ID_CLOSE, "", style=wx.BORDER_NONE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetSize((407, 245))
        self.SetBackgroundColour(wx.Colour(18, 18, 18))
        self.text_ctrl_2.SetMinSize((372, 45))
        self.text_ctrl_2.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.button_7.SetMinSize((171, 33))
        self.button_7.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.button_6.SetMinSize((88, 33))
        self.button_6.SetBackgroundColour(wx.Colour(0, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        label_5 = wx.StaticText(self, wx.ID_ANY, "New Notebook")
        label_5.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_12.Add(label_5, 0, wx.ALL | wx.FIXED_MINSIZE, 25)
        sizer_12.Add(self.text_ctrl_2, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 25)
        sizer_13.Add(self.button_7, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 20)
        sizer_13.Add((10, 20), 0, wx.BOTTOM | wx.TOP, 25)
        sizer_13.Add(self.button_6, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 20)
        sizer_12.Add(sizer_13, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_12)
        self.Layout()
        # end wxGlade

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
